
-- ============================================================
-- 2. Core Businesss KPIs
-- ============================================================


-- ============================================================
-- 1. Revenue
-- Total monetary value from completed sales over a period
-- ============================================================
SELECT 
    D.Year, D.Month, D.MonthName, 
    ROUND(SUM(F.GrossAmount),2) as GrossSales
FROM AdventureWorksDW.dbo.FactOrders F
JOIN AdventureWorksDW.dbo.DimDate D
ON F.DateKey = D.DateKey
GROUP BY D.Year, D.Month, D.MonthName
ORDER BY D.Year DESC, D.Month DESC

-- ============================================================
-- 2. Gross Profit
-- Revenue minus total cost
-- ============================================================
-- Monthly
SELECT 
    D.Year, D.Month, D.MonthName, 
    ROUND(SUM(F.CostAmount),2) as TotalCost,
    ROUND(SUM(F.GrossAmount),2) as GrossSales,
    ROUND(SUM(F.NetAmount),2) as NetSales,
    ROUND(SUM(F.ProfitAmount),2) as Profit
FROM AdventureWorksDW.dbo.FactOrders F
JOIN AdventureWorksDW.dbo.DimDate D
ON F.DateKey = D.DateKey
GROUP BY D.Year, D.Month, D.MonthName
ORDER BY D.Year DESC, D.Month DESC;

-- Quarterly
SELECT 
    D.Year, D.Quarter,
    ROUND(SUM(F.CostAmount),2) as TotalCost,
    ROUND(SUM(F.GrossAmount),2) as GrossSales,
    ROUND(SUM(F.NetAmount),2) as NetSales,
    ROUND(SUM(F.ProfitAmount),2) as Profit
FROM AdventureWorksDW.dbo.FactOrders F
JOIN AdventureWorksDW.dbo.DimDate D
ON F.DateKey = D.DateKey
GROUP BY D.Year, D.Quarter
ORDER BY D.Year DESC, D.Quarter Desc;

-- ============================================================
-- 3. Average Order Value (AOV)
-- Average monetary value generated per customer order.
-- ============================================================
SELECT
    d.Year, d.Month,d.MonthName,
    COUNT(DISTINCT f.SalesOrderID)                                    AS TotalOrders,
    ROUND(SUM(f.NetAmount),2)                                         AS Revenue,
    ROUND(SUM(f.NetAmount) / COUNT(DISTINCT f.SalesOrderID),2)        AS AOV
FROM AdventureWorksDW.dbo.FactOrders F
JOIN AdventureWorksDW.dbo.DimDate D
ON f.DateKey = d.DateKey
GROUP BY
    d.Year, d.Month,d.MonthName
ORDER BY d.Year DESC, d.Month DESC;

-- ============================================================
-- 4. Customer Lifetime Value (CLV)
-- Total revenue generated by a customer across their time
-- ============================================================
SELECT TOP (1000)
    f.CustomerKey,
    c.AccountID,
    c.Gender,
    c.Region,
    COUNT(DISTINCT f.SalesOrderID)                               AS TotalOrders,
    ROUND(SUM(f.NetAmount),2)                                    AS CLV,
    MIN(d.FullDate)                                              AS FirstPurchaseDate,
    MAX(d.FullDate)                                              AS LastPurchaseDate,
    DATEDIFF(DAY, MIN(d.FullDate), MAX(d.FullDate))              AS CustomerLifespanDays
FROM AdventureWorksDW.dbo.FactOrders f
JOIN AdventureWorksDW.dbo.DimCustomer c  
ON f.CustomerKey = c.CustomerKey
JOIN AdventureWorksDW.dbo.DimDate     d  
ON f.DateKey     = d.DateKey
GROUP BY f.CustomerKey, c.AccountID, c.Gender, c.Region
ORDER BY CLV DESC;


-- ============================================================
-- 5. Repeat Purchase Rate
-- % of customers who placed more than one order
-- ============================================================
WITH CustomerOrderCount AS (
    SELECT 
        CustomerKey,
        COUNT(DISTINCT SalesOrderID) AS TotalOrders
    FROM AdventureWorksDW.dbo.FactOrders
    GROUP BY CustomerKey),

CountStats AS (
    SELECT
        (SELECT count(CustomerKey) FROM CustomerOrderCount) AS TotalCustomers,
        SUM(CASE WHEN TotalOrders > 1 THEN 1 ELSE 0 END)  AS RepeatCustomers
    FROM CustomerOrderCount)

SELECT
    TotalCustomers,
    RepeatCustomers,
    TotalCustomers - RepeatCustomers                                AS OneTimeCustomers,
    ROUND(100* CAST(RepeatCustomers AS FLOAT)/TotalCustomers,2)     AS RepeatOrderPct 
FROM CountStats

-- ============================================================
-- 6. Profit Margin
-- Profit as a proportion of revenue
-- ============================================================
SELECT
    d.Year, d.Month, d.MonthName,
    SUM(f.NetAmount)                                                        AS Revenue,
    SUM(f.ProfitAmount)                                                     AS TotalProfit,
    ROUND( 100* CAST(SUM(f.ProfitAmount) AS FLOAT) / SUM(f.NetAmount), 2)   AS ProfitMarginPct
FROM AdventureWorksDW.dbo.FactOrders f
JOIN AdventureWorksDW.dbo.DimDate d 
ON f.DateKey = d.DateKey
GROUP BY d.Year, d.Month,d.MonthName
ORDER BY d.Year DESC, d.Month DESC;

-- ============================================================
-- 7. Revenue Growth Rate
-- Month over Month revenue change %
-- ============================================================
WITH MonthlyRevenue AS (
    SELECT
        d.Year,d.Month,d.MonthName,
        ROUND(SUM(f.NetAmount),2) AS Revenue
    FROM AdventureWorksDW.dbo.FactOrders f
    JOIN AdventureWorksDW.dbo.DimDate d ON f.DateKey = d.DateKey
    GROUP BY
        d.Year, d.Month,d.MonthName),

AddPrevious AS (
    SELECT
        Year,Month,MonthName,
        Revenue,
        LAG(Revenue, 1) OVER (ORDER BY Year, Month) AS PrevMonRevenue
    FROM MonthlyRevenue)

SELECT
    Year,Month,MonthName,
    Revenue, PrevMonRevenue,
    Revenue - PrevMonRevenue AS ChangeInRevenue,
    ROUND( 100 * ( (Revenue - PrevMonRevenue) / PrevMonRevenue ) ,2) AS GrowthRatePct
FROM AddPrevious
ORDER BY Year,Month;
