-- ============================================================
-- D. Advanced Product & Category Analytics
-- ============================================================


-- ============================================================
-- 17. Revenue Volatility for each product
-- This measure is through the standard deviation of the revenue generated by the product
-- High STDDEV -> unpredictable/volatile product
-- Low  STDDEV -> stable/consistent product
-- **NOTE**: In our dataset the ProductName is the TSHIRT+COLOR+SIZE while the ParentProductName is the TSHIRT Model
-- ============================================================

WITH MonRevenue AS (
    SELECT 
        P.ProductKey, P.ProductName, 
        SUM(F.NetAmount)                                        AS MonthlyRevenue,
        D.Year, D.Month, D.MonthName
    FROM AdventureWorksDW.dbo.FactOrders F
    JOIN AdventureWorksDW.dbo.DimDate    D  ON F.DateKey    = D.DateKey
    JOIN AdventureWorksDW.dbo.DimProduct P  ON F.ProductKey = P.ProductKey
    GROUP BY P.ProductKey, P.ProductName, D.Year, D.Month, D.MonthName
),
Metrics AS (
    SELECT
        M.ProductKey                                           AS ProductID,
        M.ProductName                                          AS Product,
        COUNT(*)                                               AS MonthsSold,
        ROUND(AVG(M.MonthlyRevenue), 2)                        AS AvgRevenue,
        ROUND(MIN(M.MonthlyRevenue), 2)                        AS MinRevenue,
        ROUND(MAX(M.MonthlyRevenue), 2)                        AS MaxRevenue,
        ROUND(STDEV(M.MonthlyRevenue), 2)                      AS STDDEV_Volatility,
        ROUND(100 * STDEV(M.MonthlyRevenue) 
                  / NULLIF(AVG(M.MonthlyRevenue), 0), 2)       AS CoeffOfVariation_Volatility
    -- a more normalized measure that takes into consideration how far off the mean is the standard deviation?
    -- CoeeffOfVar = sigma/mu
    FROM MonRevenue M
    GROUP BY M.ProductKey, M.ProductName
)
SELECT
    ProductID, Product, MonthsSold,
    AvgRevenue,MinRevenue, MaxRevenue,
    STDDEV_Volatility,
    CoeffOfVariation_Volatility,
    CASE
        WHEN CoeffOfVariation_Volatility > 100 THEN 'High Volatility'
        WHEN CoeffOfVariation_Volatility > 50  THEN 'Medium Volatility'
        ELSE                                        'Low Volatility'    END AS VolatilityBand
FROM Metrics
ORDER BY CoeffOfVariation_Volatility DESC, STDDEV_Volatility DESC;

-- ============================================================
-- 18. Trending Categories
-- Detect trending categories based on recent performance compared to historical behavior.
-- ============================================================

---------------------------------------------------------------
-- Part A. Trending Products
-- We will Compare products whose revenue increased over the last 3 months
---------------------------------------------------------------
WITH MonRev AS (
    SELECT 
        P.ProductKey, P.ProductName, 
        D.Year, D.Month, D.MonthName,
        SUM(F.NetAmount)                                        AS MonRevenue
    FROM AdventureWorksDW.dbo.FactOrders     F
    JOIN AdventureWorksDW.dbo.DimDate     D  ON F.DateKey    = D.DateKey
    JOIN AdventureWorksDW.dbo.DimProduct  P  ON F.ProductKey = P.ProductKey
    WHERE D.Year > 2024
    GROUP BY 
        P.ProductKey, P.ProductName, 
        D.Year, D.Month, D.MonthName
),
PrevMonRev AS (
    SELECT 
        M.ProductKey, M.ProductName, 
        M.Year, M.Month, M.MonthName,
        M.MonRevenue,
        LAG(M.MonRevenue, 1) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue1,
        LAG(M.MonRevenue, 2) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue2,
        LAG(M.MonRevenue, 3) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue3
    FROM MonRev AS M
),
Delta AS (
    SELECT 
        P.ProductKey, P.ProductName, 
        P.Year, P.Month, P.MonthName,
        ROUND(P.MonRevenue, 2)                                  AS MonRevenue,
        ROUND(P.PrevMonRevenue1, 2)                             AS MonRevLag1,
        ROUND(P.PrevMonRevenue2, 2)                             AS MonRevLag2,
        -- Deltas
        ROUND(P.MonRevenue      - P.PrevMonRevenue1, 2)         AS DeltaLag1,
        ROUND(P.PrevMonRevenue1 - P.PrevMonRevenue2, 2)         AS DeltaLag2,
        ROUND(P.PrevMonRevenue2 - P.PrevMonRevenue3, 2)         AS DeltaLag3,
        -- Change %
        ROUND((P.MonRevenue      - P.PrevMonRevenue1) / 
               NULLIF(P.PrevMonRevenue1, 0) * 100, 2)           AS ChangePctLag1,
        ROUND((P.PrevMonRevenue1 - P.PrevMonRevenue2) / 
               NULLIF(P.PrevMonRevenue2, 0) * 100, 2)           AS ChangePctLag2,
        ROUND((P.PrevMonRevenue2 - P.PrevMonRevenue3) / 
               NULLIF(P.PrevMonRevenue3, 0) * 100, 2)           AS ChangePctLag3
    FROM PrevMonRev P
)
SELECT 
    ProductKey, ProductName, 
    Year, Month, MonthName,
    MonRevenue,
    MonRevLag1                                                  AS 'MonRevenue_t_-1',
    MonRevLag2                                                  AS 'MonRevenue_t_-2',
    DeltaLag1                                                   AS 'DeltaRev',
    DeltaLag2                                                   AS 'DeltaRev_t_-1',
    DeltaLag3                                                   AS 'DeltaRev_t_-2',
    ChangePctLag1                                               AS 'ChangePct%',
    ChangePctLag2                                               AS 'ChangePct%_t_-1',
    ChangePctLag3                                               AS 'ChangePct%_t_-2'
FROM Delta
WHERE DeltaLag1 > 0 AND DeltaLag2 > 0 AND DeltaLag3 > 0
ORDER BY MonRevenue DESC, DeltaLag1 DESC,  ChangePctLag1 DESC


-- ------------------------------------------------------------
-- Part B. Trending Categories
-- Categories whose revenue increased over the last 3 months
-- ------------------------------------------------------------
WITH MonRev AS (
    SELECT 
        C.CategoryKey, C.CategoryName, C.ParentCategory,
        D.Year, D.Month, D.MonthName,
        SUM(F.NetAmount)                                        AS MonRevenue
    FROM AdventureWorksDW.dbo.FactOrders     F
    JOIN AdventureWorksDW.dbo.DimDate     D  ON F.DateKey    = D.DateKey
    JOIN AdventureWorksDW.dbo.DimCategory C  ON F.CategoryKey = C.CategoryKey
    WHERE D.Year > 2024
    GROUP BY 
        C.CategoryKey, C.CategoryName, C.ParentCategory,
        D.Year, D.Month, D.MonthName
),
PrevMonRev AS (
    SELECT 
        M.CategoryKey, M.CategoryName, M.ParentCategory,
        M.Year, M.Month, M.MonthName,
        M.MonRevenue,
        LAG(M.MonRevenue, 1) OVER (PARTITION BY M.CategoryKey ORDER BY M.Year, M.Month) AS PrevMonRevenue1,
        LAG(M.MonRevenue, 2) OVER (PARTITION BY M.CategoryKey ORDER BY M.Year, M.Month) AS PrevMonRevenue2,
        LAG(M.MonRevenue, 3) OVER (PARTITION BY M.CategoryKey ORDER BY M.Year, M.Month) AS PrevMonRevenue3
    FROM MonRev AS M
),
Delta AS (
    SELECT 
        P.CategoryKey, P.CategoryName, P.ParentCategory,
        P.Year, P.Month, P.MonthName,
        ROUND(P.MonRevenue, 2)                                  AS MonRevenue,
        ROUND(P.PrevMonRevenue1, 2)                             AS MonRevLag1,
        ROUND(P.PrevMonRevenue2, 2)                             AS MonRevLag2,
        -- Deltas
        ROUND(P.MonRevenue      - P.PrevMonRevenue1, 2)         AS DeltaLag1,
        ROUND(P.PrevMonRevenue1 - P.PrevMonRevenue2, 2)         AS DeltaLag2,
        ROUND(P.PrevMonRevenue2 - P.PrevMonRevenue3, 2)         AS DeltaLag3,
        -- Change %
        ROUND((P.MonRevenue      - P.PrevMonRevenue1) / 
               NULLIF(P.PrevMonRevenue1, 0) * 100, 2)           AS ChangePctLag1,
        ROUND((P.PrevMonRevenue1 - P.PrevMonRevenue2) / 
               NULLIF(P.PrevMonRevenue2, 0) * 100, 2)           AS ChangePctLag2,
        ROUND((P.PrevMonRevenue2 - P.PrevMonRevenue3) / 
               NULLIF(P.PrevMonRevenue3, 0) * 100, 2)           AS ChangePctLag3
    FROM PrevMonRev P
)
SELECT 
    CategoryKey, CategoryName, ParentCategory,
    Year, Month, MonthName,
    MonRevenue,
    MonRevLag1                                                  AS 'MonRevenue_t_-1',
    MonRevLag2                                                  AS 'MonRevenue_t_-2',
    DeltaLag1                                                   AS 'DeltaRev',
    DeltaLag2                                                   AS 'DeltaRev_t_-1',
    DeltaLag3                                                   AS 'DeltaRev_t_-2',
    ChangePctLag1                                               AS 'ChangePct%',
    ChangePctLag2                                               AS 'ChangePct%_t_-1',
    ChangePctLag3                                               AS 'ChangePct%_t_-2'
FROM Delta
WHERE DeltaLag1 > 0 AND DeltaLag2 > 0 AND DeltaLag3 > 0
ORDER BY MonRevenue DESC, DeltaLag1 DESC,  ChangePctLag1 DESC


-- ============================================================
-- 19. Seasonality Analysis
-- Compare the same month across different years
-- ============================================================

-- ------------------------------------------------------------
-- Part A. Month over Years -> (Pivoted)
-- Rows = Months, Columns = Years
-- ------------------------------------------------------------
WITH MonthlyRevenue AS (
    SELECT
        D.Month, D.MonthName, D.Year,
        SUM(F.NetAmount)                                        AS Revenue
    FROM AdventureWorksDW.dbo.FactOrders  F
    JOIN AdventureWorksDW.dbo.DimDate     D  ON F.DateKey = D.DateKey
    GROUP BY D.Month, D.MonthName, D.Year
),
Pivoted AS (
    SELECT
        Month, MonthName,
        SUM(CASE WHEN Year = 2022 THEN Revenue END)             AS Rev2022,
        SUM(CASE WHEN Year = 2023 THEN Revenue END)             AS Rev2023,
        SUM(CASE WHEN Year = 2024 THEN Revenue END)             AS Rev2024,
        SUM(CASE WHEN Year = 2025 THEN Revenue END)             AS Rev2025
    FROM MonthlyRevenue
    GROUP BY Month, MonthName
)
SELECT
    Month,
    MonthName,
    ROUND(Rev2022, 2)                                           AS [2022],
    ROUND(Rev2023, 2)                                           AS [2023],
    ROUND(Rev2024, 2)                                           AS [2024],
    ROUND(Rev2025, 2)                                           AS [2025],
    ROUND((Rev2023 - Rev2022) / NULLIF(Rev2022, 0) * 100, 2)   AS [Chng% 22-23],
    ROUND((Rev2024 - Rev2023) / NULLIF(Rev2023, 0) * 100, 2)   AS [Chng% 23-24],
    ROUND((Rev2025 - Rev2024) / NULLIF(Rev2024, 0) * 100, 2)   AS [Chng% 24-25]
FROM Pivoted
ORDER BY Month;


-- ------------------------------------------------------------
-- Part B. Category + Month over Years (Pivoted)
-- Rows = Category + Month, Columns = Years
-- ------------------------------------------------------------
WITH CategoryMonthlyRevenue AS (
    SELECT
        C.CategoryKey, C.CategoryName, C.ParentCategory,
        D.Month, D.MonthName, D.Year,
        SUM(F.NetAmount)                                        AS Revenue
    FROM AdventureWorksDW.dbo.FactOrders     F
    JOIN AdventureWorksDW.dbo.DimDate     D  ON F.DateKey     = D.DateKey
    JOIN AdventureWorksDW.dbo.DimCategory C  ON F.CategoryKey = C.CategoryKey
    GROUP BY 
        C.CategoryKey, C.CategoryName, C.ParentCategory, 
        D.Month, D.MonthName, D.Year
),
Pivoted AS (
    SELECT
        CategoryKey, CategoryName, ParentCategory,
        Month, MonthName,
        SUM(CASE WHEN Year = 2022 THEN Revenue END)             AS Rev2022,
        SUM(CASE WHEN Year = 2023 THEN Revenue END)             AS Rev2023,
        SUM(CASE WHEN Year = 2024 THEN Revenue END)             AS Rev2024,
        SUM(CASE WHEN Year = 2025 THEN Revenue END)             AS Rev2025
    FROM CategoryMonthlyRevenue
    GROUP BY 
        CategoryKey, CategoryName, ParentCategory, 
        Month, MonthName
)
SELECT
    CategoryKey, CategoryName, ParentCategory,
    Month, MonthName,
    ROUND(Rev2022, 2)                                           AS [2022],
    ROUND(Rev2023, 2)                                           AS [2023],
    ROUND(Rev2024, 2)                                           AS [2024],
    ROUND(Rev2025, 2)                                           AS [2025],
    ROUND((Rev2023 - Rev2022) / NULLIF(Rev2022, 0) * 100, 2)   AS [Chng% 22-23],
    ROUND((Rev2024 - Rev2023) / NULLIF(Rev2023, 0) * 100, 2)   AS [Chng% 23-24],
    ROUND((Rev2025 - Rev2024) / NULLIF(Rev2024, 0) * 100, 2)   AS [Chng% 24-25]
FROM Pivoted
ORDER BY CategoryKey, Month;

-- ============================================================
-- 20. Profit Consistency
-- Measures how consistently profitable each product is
-- Uses standard deviation of monthly profit
-- ============================================================
WITH MonthlyProductProfit AS (
    SELECT
        f.ProductKey,
        p.ProductName,
        p.ParentProductName,
        d.Year,
        d.Month,
        SUM(f.ProfitAmount) AS MonthlyProfit
    FROM AdventureWorksDW.dbo.FactOrders f
    JOIN AdventureWorksDW.dbo.DimProduct p ON f.ProductKey = p.ProductKey
    JOIN AdventureWorksDW.dbo.DimDate    d ON f.DateKey    = d.DateKey
    GROUP BY f.ProductKey, p.ProductName, p.ParentProductName, d.Year, d.Month
),
Metrics AS (
    SELECT
        ProductKey,
        ProductName,
        ParentProductName,
        -- Profitability metrics
        COUNT(*)                                                 AS ActiveMonths,
        ROUND(AVG(MonthlyProfit), 2)                             AS AvgMonthlyProfit,
        ROUND(STDEV(MonthlyProfit), 2)                           AS ProfitStdDev,
        ROUND(100 * STDEV(MonthlyProfit) 
                    / NULLIF(ABS(AVG(MonthlyProfit)), 0), 2)     AS ProfitCoeffOfVar,
        -- Monthly trends
        SUM(CASE WHEN MonthlyProfit >  0 THEN 1 ELSE 0 END)      AS ProfitableMonths,
        SUM(CASE WHEN MonthlyProfit <= 0 THEN 1 ELSE 0 END)      AS LossMonths,
        -- Consistency score 
        ROUND( 100*
               CAST(SUM(CASE WHEN MonthlyProfit > 0 THEN 1 ELSE 0 END) AS FLOAT)
                 / COUNT(*) 
                 , 2)                                            AS ProfitConsistencyPct
    FROM MonthlyProductProfit
    GROUP BY ProductKey, ProductName, ParentProductName
)


SELECT
    -- Attributes
    ProductKey,
    ProductName,
    ParentProductName,
    -- Metrics
    ActiveMonths,
    ProfitableMonths,
    LossMonths,
    -- Performance Classification
    AvgMonthlyProfit,
    ProfitStdDev,
    ProfitCoeffOfVar,
    ProfitConsistencyPct,
    CASE
        WHEN ProfitConsistencyPct >= 90 THEN 'Highly Consistent'
        WHEN ProfitConsistencyPct >= 75 THEN 'Moderately Consistent'
        WHEN ProfitConsistencyPct >= 50 THEN 'Mildly Consistent'
        WHEN ProfitConsistencyPct >= 0 THEN  'Inconsistent'
        ELSE                                 'Losing'
    END AS ConsistencyBand
FROM Metrics
ORDER BY ProfitConsistencyPct DESC, AvgMonthlyProfit DESC;


-- ============================================================
-- 21. Sustained Revenue Decline
-- Products with consecutive 3 and 2 months of declining revenue
-- ============================================================

-- Aggregate over months
WITH MonRev AS (
    SELECT 
        P.ProductKey, P.ProductName, 
        D.Year, D.Month, D.MonthName,
        SUM(F.NetAmount) AS MonRevenue
    FROM AdventureWorksDW.dbo.FactOrders F
    JOIN AdventureWorksDW.dbo.DimDate D    ON F.DateKey = D.DateKey
    JOIN AdventureWorksDW.dbo.DimProduct P ON F.ProductKey = P.ProductKey
    WHERE D.Year = 2025
    GROUP BY P.ProductKey, P.ProductName, D.Year, D.Month, D.MonthName
),
-- Add Lags
PrevMonRev AS (
    SELECT 
        M.ProductKey, M.ProductName, 
        M.Year, M.Month, M.MonthName,
        M.MonRevenue,
        LAG(M.MonRevenue, 1) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue1,
        LAG(M.MonRevenue, 2) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue2,
        LAG(M.MonRevenue, 3) OVER (PARTITION BY M.ProductKey ORDER BY M.Year, M.Month) AS PrevMonRevenue3
    FROM MonRev AS M
),
-- Get latest month per product
MaxFilter AS (
    SELECT ProductKey, MAX(Month) AS MaxMonth
    FROM PrevMonRev
    GROUP BY ProductKey
),
-- Reduce each product to a single row
ReducedTable AS (
    SELECT P.* 
    FROM PrevMonRev P
    JOIN MaxFilter M ON P.ProductKey = M.ProductKey AND P.Month = M.MaxMonth
),
-- Calculate deltas and decline rates
Delta AS (
    SELECT 
        R.ProductKey, R.ProductName, 
        R.Year, R.Month, R.MonthName,
        ROUND(R.MonRevenue, 2)                                      AS MonRevenue,
        ROUND(R.PrevMonRevenue1, 2)                                 AS MonRevLag1,
        ROUND(R.PrevMonRevenue2, 2)                                 AS MonRevLag2,
        -- Change in Sales Amount
        ROUND(R.MonRevenue      - R.PrevMonRevenue1, 2)             AS DeltaLag1,
        ROUND(R.PrevMonRevenue1 - R.PrevMonRevenue2, 2)             AS DeltaLag2,
        ROUND(R.PrevMonRevenue2 - R.PrevMonRevenue3, 2)             AS DeltaLag3,
        -- Decline rates as percentages
        ROUND((R.MonRevenue      - R.PrevMonRevenue1) / NULLIF(R.PrevMonRevenue1, 0) * 100, 2) AS DeclineRate1_Pct,
        ROUND((R.PrevMonRevenue1 - R.PrevMonRevenue2) / NULLIF(R.PrevMonRevenue2, 0) * 100, 2) AS DeclineRate2_Pct,
        ROUND((R.PrevMonRevenue2 - R.PrevMonRevenue3) / NULLIF(R.PrevMonRevenue3, 0) * 100, 2) AS DeclineRate3_Pct
    FROM ReducedTable R
),
-- Classify criticality
Criticality AS (
    SELECT *,
        -- Count how many consecutive months declined
        CASE 
            WHEN DeltaLag1 < 0 AND DeltaLag2 < 0 AND DeltaLag3 < 0  THEN 3   -- sales declined over the last 3 months
            WHEN DeltaLag1 < 0 AND DeltaLag2 < 0                    THEN 2  -- sales declined over the last 2 months
            WHEN DeltaLag1 < 0                                      THEN 1 -- sales declined last month
            ELSE 0
        END AS CntDeclineMonths,
        CASE 
            WHEN DeltaLag1 < 0 AND DeltaLag2 < 0 AND DeltaLag3 < 0 THEN 'Highly Critical'
            WHEN DeltaLag1 < 0 AND DeltaLag2 < 0                   THEN 'Moderately Critical'
            WHEN DeltaLag1 < 0                                     THEN 'Mildly Critical'
            ELSE 'No Decline'
        END AS CriticalityLabel
    FROM Delta
)

-- Final Table
SELECT 
    ProductKey, ProductName, Year, Month, MonthName,
    CntDeclineMonths,
    CriticalityLabel,
    MonRevenue          AS MonRevenue_t0,
    MonRevLag1          AS MonRevenue_t1,
    MonRevLag2          AS MonRevenue_t2,
    --DeltaLag1           AS DeltaRev_t0t1,
    --DeltaLag2           AS DeltaRev_t1t2,
    --DeltaLag3           AS DeltaRev_t2t3,
    DeclineRate1_Pct    AS DeclineRate_Pct_t0t1,
    DeclineRate2_Pct    AS DeclineRate_Pct_t1t2,
    DeclineRate3_Pct    AS DeclineRate_Pct_t2t3
FROM Criticality
WHERE CntDeclineMonths > 0 -- at least one month of decline
ORDER BY CntDeclineMonths DESC, DeclineRate1_Pct ASC;